# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.srcs/sources_1/ip/mult_64x64/mult_64x64.xci
# IP: The module: 'mult_64x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.gen/sources_1/ip/mult_64x64/mult_64x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_64x64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.srcs/sources_1/ip/mult_64x64/mult_64x64.xci
# IP: The module: 'mult_64x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.gen/sources_1/ip/mult_64x64/mult_64x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_64x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
