set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]
# set_property IOSTANDARD LVCMOS15 [get_ports {led[7]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {led[6]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {led[5]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports sw_s]
set_property IOSTANDARD LVCMOS15 [get_ports sw_rst]

set_property PACKAGE_PIN AD12 [get_ports sysclk_p]
set_property PACKAGE_PIN AB7 [get_ports sw_rst]
set_property PACKAGE_PIN AB12 [get_ports sw_s]

# set_property PACKAGE_PIN F16 [get_ports {led[7]}]
# set_property PACKAGE_PIN E18 [get_ports {led[6]}]
# set_property PACKAGE_PIN G19 [get_ports {led[5]}]
# set_property PACKAGE_PIN AE26 [get_ports {led[4]}]
set_property PACKAGE_PIN AB9 [get_ports {led[3]}]
set_property PACKAGE_PIN AC9 [get_ports {led[2]}]
set_property PACKAGE_PIN AA8 [get_ports {led[1]}]
set_property PACKAGE_PIN AB8 [get_ports {led[0]}]



set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch1[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dac_ch2[0]}]


set_property PACKAGE_PIN E20 [get_ports {dac_ch1[13]}]
set_property PACKAGE_PIN F20 [get_ports {dac_ch1[12]}]
set_property PACKAGE_PIN E21 [get_ports {dac_ch1[11]}]
set_property PACKAGE_PIN F21 [get_ports {dac_ch1[10]}]
set_property PACKAGE_PIN A22 [get_ports {dac_ch1[9]}]
set_property PACKAGE_PIN B22 [get_ports {dac_ch1[8]}]
set_property PACKAGE_PIN A18 [get_ports {dac_ch1[7]}]
set_property PACKAGE_PIN B18 [get_ports {dac_ch1[6]}]
set_property PACKAGE_PIN B19 [get_ports {dac_ch1[5]}]
set_property PACKAGE_PIN C19 [get_ports {dac_ch1[4]}]
set_property PACKAGE_PIN C16 [get_ports {dac_ch1[3]}]
set_property PACKAGE_PIN D16 [get_ports {dac_ch1[2]}]
set_property PACKAGE_PIN B17 [get_ports {dac_ch1[1]}]
set_property PACKAGE_PIN C17 [get_ports {dac_ch1[0]}]
set_property PACKAGE_PIN E30 [get_ports {dac_ch0[13]}]
set_property PACKAGE_PIN H24 [get_ports {dac_ch0[12]}]
set_property PACKAGE_PIN H25 [get_ports {dac_ch0[11]}]
set_property PACKAGE_PIN G28 [get_ports {dac_ch0[10]}]
set_property PACKAGE_PIN F28 [get_ports {dac_ch0[9]}]
set_property PACKAGE_PIN G27 [get_ports {dac_ch0[8]}]
set_property PACKAGE_PIN F27 [get_ports {dac_ch0[7]}]
set_property PACKAGE_PIN G29 [get_ports {dac_ch0[6]}]
set_property PACKAGE_PIN F30 [get_ports {dac_ch0[5]}]
set_property PACKAGE_PIN H26 [get_ports {dac_ch0[4]}]
set_property PACKAGE_PIN H27 [get_ports {dac_ch0[3]}]
set_property PACKAGE_PIN H30 [get_ports {dac_ch0[2]}]
set_property PACKAGE_PIN G30 [get_ports {dac_ch0[1]}]
set_property PACKAGE_PIN G25 [get_ports {dac_ch0[0]}]

set_property PACKAGE_PIN F17 [get_ports dac_clk2]
set_property PACKAGE_PIN A16 [get_ports dac_clk1]
set_property IOSTANDARD LVCMOS25 [get_ports dac_clk2]
set_property IOSTANDARD LVCMOS25 [get_ports dac_clk1]

set_property PACKAGE_PIN G17 [get_ports dac_wrt2]
set_property PACKAGE_PIN A17 [get_ports dac_wrt1]
set_property IOSTANDARD LVCMOS25 [get_ports dac_wrt2]
set_property IOSTANDARD LVCMOS25 [get_ports dac_wrt1]

# J3
# set_property PACKAGE_PIN F28 [get_ports {dac_ch1[13]}]
# set_property PACKAGE_PIN G28 [get_ports {dac_ch1[12]}]
# set_property PACKAGE_PIN A28 [get_ports {dac_ch1[11]}]
# set_property PACKAGE_PIN B28 [get_ports {dac_ch1[10]}]
# set_property PACKAGE_PIN A26 [get_ports {dac_ch1[9]}]
# set_property PACKAGE_PIN A25 [get_ports {dac_ch1[8]}]
# set_property PACKAGE_PIN A30 [get_ports {dac_ch1[7]}]
# set_property PACKAGE_PIN B30 [get_ports {dac_ch1[6]}]
# set_property PACKAGE_PIN C30 [get_ports {dac_ch1[5]}]
# set_property PACKAGE_PIN D29 [get_ports {dac_ch1[4]}]
# set_property PACKAGE_PIN F30 [get_ports {dac_ch1[3]}]
# set_property PACKAGE_PIN G29 [get_ports {dac_ch1[2]}]
# set_property PACKAGE_PIN G30 [get_ports {dac_ch1[1]}]
# set_property PACKAGE_PIN H30 [get_ports {dac_ch1[0]}]
# set_property PACKAGE_PIN B24 [get_ports {dac_ch0[13]}]
# set_property PACKAGE_PIN C24 [get_ports {dac_ch0[12]}]
# set_property PACKAGE_PIN A27 [get_ports {dac_ch0[11]}]
# set_property PACKAGE_PIN B27 [get_ports {dac_ch0[10]}]
# set_property PACKAGE_PIN F27 [get_ports {dac_ch0[9]}]
# set_property PACKAGE_PIN G27 [get_ports {dac_ch0[8]}]
# set_property PACKAGE_PIN B25 [get_ports {dac_ch0[7]}]
# set_property PACKAGE_PIN C25 [get_ports {dac_ch0[6]}]
# set_property PACKAGE_PIN H25 [get_ports {dac_ch0[5]}]
# set_property PACKAGE_PIN H24 [get_ports {dac_ch0[4]}]
# set_property PACKAGE_PIN H27 [get_ports {dac_ch0[3]}]
# set_property PACKAGE_PIN H26 [get_ports {dac_ch0[2]}]
# set_property PACKAGE_PIN B29 [get_ports {dac_ch0[1]}]
# set_property PACKAGE_PIN C29 [get_ports {dac_ch0[0]}]
