# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.srcs/sources_1/ip/rom_sin/rom_sin.xci
# IP: The module: 'rom_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.gen/sources_1/ip/rom_sin/rom_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.srcs/sources_1/ip/rom_sin/rom_sin.xci
# IP: The module: 'rom_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/SineCalculate/2.Firmware/SineCalculate/SineCalculate.gen/sources_1/ip/rom_sin/rom_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
