# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/mult_u64xu64/mult_u64xu64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_u64xu64 || ORIG_REF_NAME==mult_u64xu64} -quiet] -quiet

# IP: ip/mult_u18xu18/mult_u18xu18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_u18xu18 || ORIG_REF_NAME==mult_u18xu18} -quiet] -quiet

# IP: ip/cordic_sin_ip/cordic_sin_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_sin_ip || ORIG_REF_NAME==cordic_sin_ip} -quiet] -quiet
